In [289]:
import pandas as pd
import numpy as np

In [290]:
df = pd.read_csv("C://Users/user/Desktop/pet/pet-projects/ml/churn/WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [291]:
df = df.dropna(inplace=True)

cols = df.select_dtypes(include='object').columns

mask = df[cols].apply(lambda col: col.astype(str).str.strip().eq('')).any(axis=1)

df = df[~mask]

AttributeError: 'NoneType' object has no attribute 'select_dtypes'

In [ ]:
X = df.drop('Churn', axis=1).copy()
y = (df['Churn']).copy()

In [ ]:
X = X.drop('customerID', axis=1)

In [ ]:
categorical_cols = X.select_dtypes(include='object').columns.tolist()
if 'Churn' in categorical_cols:
    categorical_cols.remove('Churn')


X = pd.get_dummies(X, columns=categorical_cols, drop_first=True)

In [ ]:
X.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,0,0,1,0,0.000000,0,1,0,0,2,0,0,0,0,0,1,2,0.115423,0.383520
1,1,0,0,0,0.464789,1,0,0,2,0,2,0,0,0,1,0,3,0.385075,0.224384
2,1,0,0,0,0.014085,1,0,0,2,2,0,0,0,0,0,1,3,0.354229,0.023893
3,1,0,0,0,0.619718,0,1,0,2,0,2,2,0,0,1,0,0,0.239303,0.214275
4,0,0,0,0,0.014085,1,0,1,0,0,0,0,0,0,0,1,2,0.521891,0.141522

In [ ]:
from sklearn.preprocessing import LabelEncoder

enc = LabelEncoder()
y = enc.fit_transform(y)

In [ ]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

for col in X.columns:
    if X[col].max() > 3:
        st = MinMaxScaler()
        X[col] = st.fit_transform(X[[col]])

In [ ]:
X.shape

(7032, 19)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test =train_test_split(
    X,y,
    random_state=42,
    test_size=0.2,
    shuffle=True,
    stratify=y
)

In [ ]:
X_train.shape

(5625, 19)

In [ ]:
c = 0
for i in y_train:
    if i == 1:
        c += 1

c

1495

In [ ]:
from sklearn.dummy import DummyClassifier
from sklearn.metrics import f1_score, recall_score, precision_score

dummy = DummyClassifier()

dummy.fit(X_train, y_train)
p = dummy.predict(X_test)

f1_score(y_test, p)

0.0

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    class_weight='balanced',
    random_state=42
)
model.fit(X_train, y_train)
pred = model.predict(X_test)

pred = (np.array(pred) >= 0.4).astype(int)

print('logreg')
f1_score(y_test, pred)

logreg

0.6078028747433265

In [ ]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_smote, y_smote = smote.fit_resample(X_train, y_train)

model1 = LogisticRegression(
    class_weight='balanced',
    random_state=42
)
model1.fit(X_smote, y_smote)
pred1 = model1.predict_proba(X_test)[:, 1]

pred1 = (np.array(pred1) >= 0.4).astype(int)

print('logreg_smote')
f1_score(y_test, pred1)

logreg_smote

0.5804597701149425

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    random_state=42,
    class_weight='balanced',
    max_depth=8,
    min_samples_split=9,
    n_estimators=100,
    )


rf.fit(X_train, y_train)

pred2 = rf.predict_proba(X_test)[:, 1]

pred2 = (np.array(pred2) >= 0.5).astype(int)

print('fr')
f1_score(y_test, pred2)

fr

0.6220302375809935

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    random_state=42,
    class_weight='balanced',
    max_depth=6,
    n_estimators=1000,
    min_samples_split=5,
    )

rf.fit(X_smote, y_smote)

pred3 = rf.predict(X_test)

print('fr_smote')
f1_score(y_test, pred3)

fr_smote

0.6033402922755741

In [ ]:
from catboost import CatBoostClassifier


model3 = CatBoostClassifier(
    random_seed=42,
    learning_rate=0.01,
    loss_function='Logloss',
    eval_metric='F1',
    iterations=2000,
    depth=4,
    l2_leaf_reg=100
    )

model3.fit(X_train, y_train)
pred4 = model3.predict_proba(X_test)[:, 1]


pred4 = (np.array(pred4) >= 0.4).astype(int)
f1_score(y_test, pred4)

0:	learn: 0.4216471	total: 2.96ms	remaining: 5.91s
1:	learn: 0.4240150	total: 6.28ms	remaining: 6.27s
2:	learn: 0.5226337	total: 9.19ms	remaining: 6.12s
3:	learn: 0.5476190	total: 11.8ms	remaining: 5.91s
4:	learn: 0.5495706	total: 15.7ms	remaining: 6.25s
5:	learn: 0.5692367	total: 18.6ms	remaining: 6.2s
6:	learn: 0.5381238	total: 21.3ms	remaining: 6.07s
7:	learn: 0.5587426	total: 24.3ms	remaining: 6.06s
8:	learn: 0.5631825	total: 27.6ms	remaining: 6.1s
9:	learn: 0.5596512	total: 31ms	remaining: 6.16s
10:	learn: 0.5628220	total: 33.6ms	remaining: 6.07s
11:	learn: 0.5737578	total: 36.4ms	remaining: 6.03s
12:	learn: 0.5756286	total: 39.6ms	remaining: 6.05s
13:	learn: 0.5753000	total: 42.5ms	remaining: 6.02s
14:	learn: 0.5802469	total: 45.6ms	remaining: 6.03s
15:	learn: 0.5739737	total: 48.4ms	remaining: 6s
16:	learn: 0.5796767	total: 51ms	remaining: 5.95s
17:	learn: 0.5790285	total: 53.8ms	remaining: 5.92s
18:	learn: 0.5797546	total: 56.5ms	remaining: 5.89s
19:	learn: 0.5760122	total: 59.1ms	remaining: 5.85s
20:	learn: 0.5772327	total: 62.4ms	remaining: 5.88s
21:	learn: 0.5798095	total: 65.3ms	remaining: 5.87s
22:	learn: 0.5821347	total: 68ms	remaining: 5.85s
23:	learn: 0.5783681	total: 71.1ms	remaining: 5.85s
24:	learn: 0.5814575	total: 73.8ms	remaining: 5.83s
25:	learn: 0.5836516	total: 76.9ms	remaining: 5.84s
26:	learn: 0.5800000	total: 79.7ms	remaining: 5.83s
27:	learn: 0.5755340	total: 82.4ms	remaining: 5.8s
28:	learn: 0.5735409	total: 85.4ms	remaining: 5.81s
29:	learn: 0.5672699	total: 88.3ms	remaining: 5.8s
30:	learn: 0.5651144	total: 90.9ms	remaining: 5.77s
31:	learn: 0.5690738	total: 93.9ms	remaining: 5.77s
32:	learn: 0.5673647	total: 96.6ms	remaining: 5.76s
33:	learn: 0.5654243	total: 99.4ms	remaining: 5.75s
34:	learn: 0.5607328	total: 102ms	remaining: 5.75s
35:	learn: 0.5568910	total: 105ms	remaining: 5.73s
36:	learn: 0.5538585	total: 108ms	remaining: 5.72s
37:	learn: 0.5541683	total: 111ms	remaining: 5.72s
38:	learn: 0.5600000	total: 114ms	remaining: 5.71s
39:	learn: 0.5502219	total: 117ms	remaining: 5.74s
40:	learn: 0.5524729	total: 120ms	remaining: 5.73s
41:	learn: 0.5551086	total: 123ms	remaining: 5.72s
42:	learn: 0.5499393	total: 126ms	remaining: 5.71s
43:	learn: 0.5554212	total: 128ms	remaining: 5.71s
44:	learn: 0.5568090	total: 131ms	remaining: 5.7s
45:	learn: 0.5570740	total: 134ms	remaining: 5.7s
46:	learn: 0.5598718	total: 137ms	remaining: 5.7s
47:	learn: 0.5590709	total: 140ms	remaining: 5.69s
48:	learn: 0.5584936	total: 143ms	remaining: 5.7s
49:	learn: 0.5581395	total: 146ms	remaining: 5.7s
50:	learn: 0.5583634	total: 150ms	remaining: 5.72s
51:	learn: 0.5582329	total: 153ms	remaining: 5.72s
52:	learn: 0.5568501	total: 156ms	remaining: 5.73s
53:	learn: 0.5555556	total: 159ms	remaining: 5.72s
54:	learn: 0.5560032	total: 162ms	remaining: 5.72s
55:	learn: 0.5564938	total: 165ms	remaining: 5.72s
56:	learn: 0.5559131	total: 168ms	remaining: 5.72s
57:	learn: 0.5547918	total: 171ms	remaining: 5.71s
58:	learn: 0.5550162	total: 174ms	remaining: 5.72s
59:	learn: 0.5544314	total: 177ms	remaining: 5.71s
60:	learn: 0.5550589	total: 180ms	remaining: 5.71s
61:	learn: 0.5557364	total: 183ms	remaining: 5.71s
62:	learn: 0.5484401	total: 186ms	remaining: 5.73s
63:	learn: 0.5421488	total: 190ms	remaining: 5.74s
64:	learn: 0.5435052	total: 194ms	remaining: 5.77s
65:	learn: 0.5434335	total: 197ms	remaining: 5.78s
66:	learn: 0.5410987	total: 200ms	remaining: 5.77s
67:	learn: 0.5437294	total: 203ms	remaining: 5.78s
68:	learn: 0.5492611	total: 207ms	remaining: 5.78s
69:	learn: 0.5473943	total: 210ms	remaining: 5.79s
70:	learn: 0.5443299	total: 213ms	remaining: 5.79s
71:	learn: 0.5450803	total: 217ms	remaining: 5.8s
72:	learn: 0.5477655	total: 220ms	remaining: 5.81s
73:	learn: 0.5518367	total: 223ms	remaining: 5.81s
74:	learn: 0.5543346	total: 228ms	remaining: 5.85s
75:	learn: 0.5536078	total: 231ms	remaining: 5.86s
76:	learn: 0.5530179	total: 235ms	remaining: 5.86s
77:	learn: 0.5519772	total: 238ms	remaining: 5.86s
78:	learn: 0.5483607	total: 242ms	remaining: 5.87s
79:	learn: 0.5459770	total: 245ms	remaining: 5.88s
80:	learn: 0.5447823	total: 248ms	remaining: 5.89s
81:	learn: 0.5500613	total: 252ms	remaining: 5.89s
82:	learn: 0.5432099	total: 256ms	remaining: 5.9s
83:	learn: 0.5445585	total: 259ms	remaining: 5.91s
84:	learn: 0.5444079	total: 262ms	remaining: 5.91s
85:	learn: 0.5447823	total: 267ms	remaining: 5.93s
86:	learn: 0.5518367	total: 270ms	remaining: 5.94s
87:	learn: 0.5526531	total: 274ms	remaining: 5.95s
88:	learn: 0.5490196	total: 277ms	remaining: 5.95s
89:	learn: 0.5474632	total: 280ms	remaining: 5.95s
90:	learn: 0.5498366	total: 290ms	remaining: 6.08s
91:	learn: 0.5433621	total: 296ms	remaining: 6.14s
92:	learn: 0.5429864	total: 302ms	remaining: 6.2s
93:	learn: 0.5441841	total: 306ms	remaining: 6.21s
94:	learn: 0.5447823	total: 310ms	remaining: 6.22s
95:	learn: 0.5453799	total: 314ms	remaining: 6.23s
96:	learn: 0.5438091	total: 318ms	remaining: 6.24s
97:	learn: 0.5432099	total: 322ms	remaining: 6.25s
98:	learn: 0.5405851	total: 328ms	remaining: 6.3s
99:	learn: 0.5429864	total: 332ms	remaining: 6.3s
100:	learn: 0.5421637	total: 335ms	remaining: 6.3s
101:	learn: 0.5439606	total: 339ms	remaining: 6.3s
102:	learn: 0.5418719	total: 342ms	remaining: 6.3s
103:	learn: 0.5452313	total: 347ms	remaining: 6.33s
104:	learn: 0.5434426	total: 354ms	remaining: 6.39s
105:	learn: 0.5448587	total: 357ms	remaining: 6.38s
106:	learn: 0.5444126	total: 361ms	remaining: 6.38s
107:	learn: 0.5438165	total: 364ms	remaining: 6.37s
108:	learn: 0.5444126	total: 368ms	remaining: 6.39s
109:	learn: 0.5445626	total: 373ms	remaining: 6.4s
110:	learn: 0.5451573	total: 377ms	remaining: 6.42s
111:	learn: 0.5465686	total: 381ms	remaining: 6.42s
112:	learn: 0.5465686	total: 385ms	remaining: 6.43s
113:	learn: 0.5473083	total: 389ms	remaining: 6.43s
114:	learn: 0.5462699	total: 392ms	remaining: 6.43s
115:	learn: 0.5479005	total: 397ms	remaining: 6.45s
116:	learn: 0.5446392	total: 401ms	remaining: 6.45s
117:	learn: 0.5467156	total: 405ms	remaining: 6.46s
118:	learn: 0.5462699	total: 409ms	remaining: 6.46s
119:	learn: 0.5460473	total: 413ms	remaining: 6.47s
120:	learn: 0.5448613	total: 418ms	remaining: 6.49s
121:	learn: 0.5458248	total: 422ms	remaining: 6.5s
122:	learn: 0.5464169	total: 427ms	remaining: 6.52s
123:	learn: 0.5452323	total: 432ms	remaining: 6.53s
124:	learn: 0.5461195	total: 436ms	remaining: 6.54s
125:	learn: 0.5481903	total: 440ms	remaining: 6.54s
126:	learn: 0.5487013	total: 443ms	remaining: 6.53s
127:	learn: 0.5514170	total: 447ms	remaining: 6.54s
128:	learn: 0.5525890	total: 451ms	remaining: 6.54s
129:	learn: 0.5509709	total: 455ms	remaining: 6.55s
130:	learn: 0.5512769	total: 459ms	remaining: 6.54s
131:	learn: 0.5520876	total: 462ms	remaining: 6.54s
132:	learn: 0.5523114	total: 467ms	remaining: 6.55s
133:	learn: 0.5521721	total: 471ms	remaining: 6.56s
134:	learn: 0.5545197	total: 476ms	remaining: 6.57s
135:	learn: 0.5515841	total: 479ms	remaining: 6.57s
136:	learn: 0.5515841	total: 483ms	remaining: 6.57s
137:	learn: 0.5529842	total: 488ms	remaining: 6.58s
138:	learn: 0.5523964	total: 492ms	remaining: 6.58s
139:	learn: 0.5533469	total: 496ms	remaining: 6.59s
140:	learn: 0.5525355	total: 501ms	remaining: 6.6s
141:	learn: 0.5541582	total: 505ms	remaining: 6.61s
142:	learn: 0.5542950	total: 511ms	remaining: 6.64s
143:	learn: 0.5554656	total: 516ms	remaining: 6.66s
144:	learn: 0.5560502	total: 521ms	remaining: 6.67s
145:	learn: 0.5556005	total: 526ms	remaining: 6.68s
146:	learn: 0.5564092	total: 531ms	remaining: 6.7s
147:	learn: 0.5564092	total: 536ms	remaining: 6.71s
148:	learn: 0.5560936	total: 542ms	remaining: 6.73s
149:	learn: 0.5563181	total: 546ms	remaining: 6.73s
150:	learn: 0.5576148	total: 554ms	remaining: 6.78s
151:	learn: 0.5579710	total: 559ms	remaining: 6.79s
152:	learn: 0.5587762	total: 565ms	remaining: 6.82s
153:	learn: 0.5585513	total: 571ms	remaining: 6.84s
154:	learn: 0.5583266	total: 576ms	remaining: 6.85s
155:	learn: 0.5589415	total: 582ms	remaining: 6.88s
156:	learn: 0.5588117	total: 587ms	remaining: 6.89s
157:	learn: 0.5592949	total: 592ms	remaining: 6.9s
158:	learn: 0.5603206	total: 598ms	remaining: 6.92s
159:	learn: 0.5608974	total: 604ms	remaining: 6.95s
160:	learn: 0.5606728	total: 609ms	remaining: 6.96s
161:	learn: 0.5612490	total: 614ms	remaining: 6.97s
162:	learn: 0.5608000	total: 620ms	remaining: 6.99s
163:	learn: 0.5608000	total: 626ms	remaining: 7.01s
164:	learn: 0.5604484	total: 632ms	remaining: 7.03s
165:	learn: 0.5604484	total: 636ms	remaining: 7.03s
166:	learn: 0.5604484	total: 642ms	remaining: 7.05s
167:	learn: 0.5604484	total: 647ms	remaining: 7.06s
168:	learn: 0.5613754	total: 652ms	remaining: 7.07s
169:	learn: 0.5625250	total: 657ms	remaining: 7.07s
170:	learn: 0.5625250	total: 662ms	remaining: 7.08s
171:	learn: 0.5627498	total: 667ms	remaining: 7.08s
172:	learn: 0.5627498	total: 673ms	remaining: 7.1s
173:	learn: 0.5638978	total: 677ms	remaining: 7.1s
174:	learn: 0.5633240	total: 682ms	remaining: 7.11s
175:	learn: 0.5628743	total: 686ms	remaining: 7.11s
176:	learn: 0.5625250	total: 691ms	remaining: 7.11s
177:	learn: 0.5636727	total: 697ms	remaining: 7.13s
178:	learn: 0.5636727	total: 705ms	remaining: 7.17s
179:	learn: 0.5648185	total: 712ms	remaining: 7.2s
180:	learn: 0.5638978	total: 719ms	remaining: 7.23s
181:	learn: 0.5633240	total: 726ms	remaining: 7.25s
182:	learn: 0.5633240	total: 732ms	remaining: 7.27s
183:	learn: 0.5644711	total: 740ms	remaining: 7.3s
184:	learn: 0.5644711	total: 747ms	remaining: 7.33s
185:	learn: 0.5658420	total: 754ms	remaining: 7.35s
186:	learn: 0.5652695	total: 760ms	remaining: 7.37s
187:	learn: 0.5652695	total: 767ms	remaining: 7.39s
188:	learn: 0.5650439	total: 772ms	remaining: 7.39s
189:	learn: 0.5637959	total: 777ms	remaining: 7.4s
190:	learn: 0.5645933	total: 782ms	remaining: 7.41s
191:	learn: 0.5645933	total: 787ms	remaining: 7.41s
192:	learn: 0.5640207	total: 793ms	remaining: 7.43s
193:	learn: 0.5644711	total: 797ms	remaining: 7.42s
194:	learn: 0.5645933	total: 801ms	remaining: 7.42s
195:	learn: 0.5651654	total: 806ms	remaining: 7.42s
196:	learn: 0.5657371	total: 811ms	remaining: 7.42s
197:	learn: 0.5665339	total: 817ms	remaining: 7.43s
198:	learn: 0.5665339	total: 822ms	remaining: 7.43s
199:	learn: 0.5657371	total: 828ms	remaining: 7.45s
200:	learn: 0.5665339	total: 834ms	remaining: 7.47s
201:	learn: 0.5659625	total: 841ms	remaining: 7.48s
202:	learn: 0.5657371	total: 848ms	remaining: 7.5s
203:	learn: 0.5663082	total: 853ms	remaining: 7.51s
204:	learn: 0.5668790	total: 859ms	remaining: 7.53s
205:	learn: 0.5660828	total: 867ms	remaining: 7.55s
206:	learn: 0.5666534	total: 874ms	remaining: 7.57s
207:	learn: 0.5655117	total: 881ms	remaining: 7.59s
208:	learn: 0.5672235	total: 887ms	remaining: 7.6s
209:	learn: 0.5679110	total: 894ms	remaining: 7.62s
210:	learn: 0.5684796	total: 898ms	remaining: 7.62s
211:	learn: 0.5673421	total: 905ms	remaining: 7.63s
212:	learn: 0.5673421	total: 912ms	remaining: 7.65s
213:	learn: 0.5690476	total: 921ms	remaining: 7.68s
214:	learn: 0.5692735	total: 927ms	remaining: 7.7s
215:	learn: 0.5683625	total: 933ms	remaining: 7.7s
216:	learn: 0.5681367	total: 938ms	remaining: 7.71s
217:	learn: 0.5673421	total: 942ms	remaining: 7.7s
218:	learn: 0.5690476	total: 948ms	remaining: 7.71s
219:	learn: 0.5690476	total: 954ms	remaining: 7.72s
220:	learn: 0.5690476	total: 960ms	remaining: 7.73s
221:	learn: 0.5707491	total: 969ms	remaining: 7.76s
222:	learn: 0.5707491	total: 977ms	remaining: 7.79s
223:	learn: 0.5709754	total: 986ms	remaining: 7.81s
224:	learn: 0.5724466	total: 993ms	remaining: 7.83s
225:	learn: 0.5713154	total: 1000ms	remaining: 7.85s
226:	learn: 0.5725583	total: 1.01s	remaining: 7.87s
227:	learn: 0.5725583	total: 1.02s	remaining: 7.9s
228:	learn: 0.5737964	total: 1.02s	remaining: 7.92s
229:	learn: 0.5740229	total: 1.03s	remaining: 7.94s
230:	learn: 0.5743590	total: 1.04s	remaining: 7.97s
231:	learn: 0.5754829	total: 1.05s	remaining: 7.99s
232:	learn: 0.5746945	total: 1.05s	remaining: 8s
233:	learn: 0.5752561	total: 1.06s	remaining: 8.02s
234:	learn: 0.5735700	total: 1.07s	remaining: 8.04s
235:	learn: 0.5752561	total: 1.08s	remaining: 8.05s
236:	learn: 0.5746945	total: 1.08s	remaining: 8.07s
237:	learn: 0.5746945	total: 1.09s	remaining: 8.1s
238:	learn: 0.5741325	total: 1.1s	remaining: 8.11s
239:	learn: 0.5746945	total: 1.11s	remaining: 8.14s
240:	learn: 0.5752561	total: 1.12s	remaining: 8.18s
241:	learn: 0.5752561	total: 1.13s	remaining: 8.2s
242:	learn: 0.5752561	total: 1.14s	remaining: 8.22s
243:	learn: 0.5752561	total: 1.15s	remaining: 8.25s
244:	learn: 0.5758173	total: 1.15s	remaining: 8.27s
245:	learn: 0.5761511	total: 1.16s	remaining: 8.29s
246:	learn: 0.5767113	total: 1.17s	remaining: 8.3s
247:	learn: 0.5755906	total: 1.18s	remaining: 8.32s
248:	learn: 0.5770440	total: 1.19s	remaining: 8.33s
249:	learn: 0.5764845	total: 1.19s	remaining: 8.33s
250:	learn: 0.5769382	total: 1.2s	remaining: 8.35s
251:	learn: 0.5771654	total: 1.21s	remaining: 8.38s
252:	learn: 0.5772709	total: 1.22s	remaining: 8.4s
253:	learn: 0.5767113	total: 1.22s	remaining: 8.4s
254:	learn: 0.5789474	total: 1.23s	remaining: 8.42s
255:	learn: 0.5783890	total: 1.24s	remaining: 8.45s
256:	learn: 0.5783890	total: 1.25s	remaining: 8.45s
257:	learn: 0.5780574	total: 1.25s	remaining: 8.46s
258:	learn: 0.5789474	total: 1.26s	remaining: 8.48s
259:	learn: 0.5791749	total: 1.27s	remaining: 8.51s
260:	learn: 0.5791749	total: 1.28s	remaining: 8.52s
261:	learn: 0.5797329	total: 1.29s	remaining: 8.54s
262:	learn: 0.5806199	total: 1.3s	remaining: 8.56s
263:	learn: 0.5803922	total: 1.3s	remaining: 8.56s
264:	learn: 0.5815047	total: 1.31s	remaining: 8.58s
265:	learn: 0.5806199	total: 1.32s	remaining: 8.6s
266:	learn: 0.5817327	total: 1.32s	remaining: 8.6s
267:	learn: 0.5839530	total: 1.33s	remaining: 8.61s
268:	learn: 0.5839530	total: 1.34s	remaining: 8.61s
269:	learn: 0.5837246	total: 1.34s	remaining: 8.61s
270:	learn: 0.5837246	total: 1.35s	remaining: 8.61s
271:	learn: 0.5837246	total: 1.35s	remaining: 8.61s
272:	learn: 0.5834963	total: 1.36s	remaining: 8.61s
273:	learn: 0.5848319	total: 1.37s	remaining: 8.61s
274:	learn: 0.5853849	total: 1.37s	remaining: 8.6s
275:	learn: 0.5859375	total: 1.38s	remaining: 8.62s
276:	learn: 0.5846034	total: 1.39s	remaining: 8.62s
277:	learn: 0.5843750	total: 1.39s	remaining: 8.63s
278:	learn: 0.5857087	total: 1.4s	remaining: 8.64s
279:	learn: 0.5854801	total: 1.41s	remaining: 8.64s
280:	learn: 0.5852517	total: 1.41s	remaining: 8.65s
281:	learn: 0.5861263	total: 1.42s	remaining: 8.67s
282:	learn: 0.5850234	total: 1.43s	remaining: 8.69s
283:	learn: 0.5855750	total: 1.44s	remaining: 8.7s
284:	learn: 0.5861263	total: 1.45s	remaining: 8.7s
285:	learn: 0.5861263	total: 1.45s	remaining: 8.71s
286:	learn: 0.5861263	total: 1.46s	remaining: 8.71s
287:	learn: 0.5855750	total: 1.46s	remaining: 8.7s
288:	learn: 0.5864486	total: 1.47s	remaining: 8.68s
289:	learn: 0.5864486	total: 1.47s	remaining: 8.67s
290:	learn: 0.5864486	total: 1.47s	remaining: 8.65s
291:	learn: 0.5864486	total: 1.48s	remaining: 8.63s
292:	learn: 0.5864486	total: 1.48s	remaining: 8.62s
293:	learn: 0.5864486	total: 1.48s	remaining: 8.6s
294:	learn: 0.5864486	total: 1.48s	remaining: 8.58s
295:	learn: 0.5864486	total: 1.49s	remaining: 8.56s
296:	learn: 0.5864486	total: 1.49s	remaining: 8.55s
297:	learn: 0.5862203	total: 1.49s	remaining: 8.53s
298:	learn: 0.5858979	total: 1.5s	remaining: 8.52s
299:	learn: 0.5858979	total: 1.5s	remaining: 8.51s
300:	learn: 0.5858979	total: 1.5s	remaining: 8.49s
301:	learn: 0.5858979	total: 1.51s	remaining: 8.47s
302:	learn: 0.5856698	total: 1.51s	remaining: 8.46s
303:	learn: 0.5867704	total: 1.51s	remaining: 8.44s
304:	learn: 0.5875486	total: 1.52s	remaining: 8.45s
305:	learn: 0.5875486	total: 1.52s	remaining: 8.45s
306:	learn: 0.5878694	total: 1.53s	remaining: 8.44s
307:	learn: 0.5875486	total: 1.53s	remaining: 8.44s
308:	learn: 0.5880980	total: 1.54s	remaining: 8.44s
309:	learn: 0.5874126	total: 1.55s	remaining: 8.44s
310:	learn: 0.5881896	total: 1.55s	remaining: 8.44s
311:	learn: 0.5879612	total: 1.56s	remaining: 8.44s
312:	learn: 0.5885093	total: 1.57s	remaining: 8.45s
313:	learn: 0.5888285	total: 1.57s	remaining: 8.45s
314:	learn: 0.5893757	total: 1.58s	remaining: 8.45s
315:	learn: 0.5893757	total: 1.59s	remaining: 8.45s
316:	learn: 0.5893757	total: 1.59s	remaining: 8.45s
317:	learn: 0.5889190	total: 1.6s	remaining: 8.45s
318:	learn: 0.5886909	total: 1.6s	remaining: 8.45s
319:	learn: 0.5889190	total: 1.61s	remaining: 8.46s
320:	learn: 0.5889190	total: 1.62s	remaining: 8.46s
321:	learn: 0.5889190	total: 1.63s	remaining: 8.47s
322:	learn: 0.5894655	total: 1.63s	remaining: 8.47s
323:	learn: 0.5886909	total: 1.64s	remaining: 8.46s
324:	learn: 0.5892373	total: 1.64s	remaining: 8.46s
325:	learn: 0.5890093	total: 1.65s	remaining: 8.47s
326:	learn: 0.5884630	total: 1.65s	remaining: 8.46s
327:	learn: 0.5890093	total: 1.66s	remaining: 8.47s
328:	learn: 0.5898724	total: 1.67s	remaining: 8.47s
329:	learn: 0.5901893	total: 1.67s	remaining: 8.48s
330:	learn: 0.5901893	total: 1.68s	remaining: 8.48s
331:	learn: 0.5901893	total: 1.69s	remaining: 8.48s
332:	learn: 0.5904173	total: 1.69s	remaining: 8.48s
333:	learn: 0.5898724	total: 1.7s	remaining: 8.48s
334:	learn: 0.5898724	total: 1.71s	remaining: 8.49s
335:	learn: 0.5906455	total: 1.72s	remaining: 8.5s
336:	learn: 0.5906455	total: 1.72s	remaining: 8.5s
337:	learn: 0.5904173	total: 1.73s	remaining: 8.51s
338:	learn: 0.5901893	total: 1.74s	remaining: 8.5s
339:	learn: 0.5907336	total: 1.74s	remaining: 8.51s
340:	learn: 0.5907336	total: 1.75s	remaining: 8.5s
341:	learn: 0.5902778	total: 1.75s	remaining: 8.5s
342:	learn: 0.5910494	total: 1.76s	remaining: 8.51s
343:	learn: 0.5908214	total: 1.77s	remaining: 8.51s
344:	learn: 0.5908214	total: 1.77s	remaining: 8.5s
345:	learn: 0.5908214	total: 1.78s	remaining: 8.5s
346:	learn: 0.5908214	total: 1.78s	remaining: 8.5s
347:	learn: 0.5908214	total: 1.79s	remaining: 8.5s
348:	learn: 0.5908214	total: 1.8s	remaining: 8.5s
349:	learn: 0.5908214	total: 1.8s	remaining: 8.5s
350:	learn: 0.5908214	total: 1.81s	remaining: 8.49s
351:	learn: 0.5908214	total: 1.81s	remaining: 8.49s
352:	learn: 0.5913647	total: 1.82s	remaining: 8.49s
353:	learn: 0.5916795	total: 1.82s	remaining: 8.48s
354:	learn: 0.5916795	total: 1.83s	remaining: 8.49s
355:	learn: 0.5916795	total: 1.84s	remaining: 8.49s
356:	learn: 0.5914517	total: 1.84s	remaining: 8.49s
357:	learn: 0.5914517	total: 1.85s	remaining: 8.49s
358:	learn: 0.5914517	total: 1.86s	remaining: 8.5s
359:	learn: 0.5914517	total: 1.87s	remaining: 8.51s
360:	learn: 0.5919938	total: 1.88s	remaining: 8.52s
361:	learn: 0.5917661	total: 1.88s	remaining: 8.52s
362:	learn: 0.5919938	total: 1.89s	remaining: 8.53s
363:	learn: 0.5922218	total: 1.9s	remaining: 8.54s
364:	learn: 0.5922218	total: 1.91s	remaining: 8.54s
365:	learn: 0.5922218	total: 1.91s	remaining: 8.54s
366:	learn: 0.5919938	total: 1.92s	remaining: 8.56s
367:	learn: 0.5930769	total: 1.93s	remaining: 8.57s
368:	learn: 0.5928489	total: 1.94s	remaining: 8.57s
369:	learn: 0.5930769	total: 1.95s	remaining: 8.57s
370:	learn: 0.5930769	total: 1.95s	remaining: 8.57s
371:	learn: 0.5936178	total: 1.96s	remaining: 8.56s
372:	learn: 0.5933897	total: 1.96s	remaining: 8.56s
373:	learn: 0.5928489	total: 1.97s	remaining: 8.56s
374:	learn: 0.5926211	total: 1.98s	remaining: 8.56s
375:	learn: 0.5931617	total: 1.98s	remaining: 8.56s
376:	learn: 0.5928489	total: 1.99s	remaining: 8.55s
377:	learn: 0.5928489	total: 1.99s	remaining: 8.55s
378:	learn: 0.5930769	total: 2s	remaining: 8.55s
379:	learn: 0.5930769	total: 2s	remaining: 8.55s
380:	learn: 0.5939301	total: 2.01s	remaining: 8.55s
381:	learn: 0.5936178	total: 2.02s	remaining: 8.55s
382:	learn: 0.5941583	total: 2.02s	remaining: 8.55s
383:	learn: 0.5937020	total: 2.03s	remaining: 8.54s
384:	learn: 0.5947813	total: 2.04s	remaining: 8.54s
385:	learn: 0.5947813	total: 2.04s	remaining: 8.54s
386:	learn: 0.5942418	total: 2.05s	remaining: 8.54s

0.6180904522613065

In [ ]:
X.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,0,0,1,0,0.000000,0,1,0,0,2,0,0,0,0,0,1,2,0.115423,0.383520
1,1,0,0,0,0.464789,1,0,0,2,0,2,0,0,0,1,0,3,0.385075,0.224384
2,1,0,0,0,0.014085,1,0,0,2,2,0,0,0,0,0,1,3,0.354229,0.023893
3,1,0,0,0,0.619718,0,1,0,2,0,2,2,0,0,1,0,0,0.239303,0.214275
4,0,0,0,0,0.014085,1,0,1,0,0,0,0,0,0,0,1,2,0.521891,0.141522

In [ ]:
cat_fet = X.columns

fet_idx = np.arange(len(cat_fet))
fet_idx = np.delete( fet_idx, [4, 17, 18])

In [ ]:
fet_idx

array([ 0,  1,  2,  3,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
from imblearn.over_sampling import SMOTENC

nc = SMOTENC(categorical_features = fet_idx.tolist(), random_state= 42)

X_nc, y_nc = nc.fit_resample(X_train, y_train)

In [ ]:
model_nc1 = LogisticRegression(
    random_state=42,
    class_weight='balanced',
)

model_nc1.fit(X_nc, y_nc)
pred_nc1 = model_nc1.predict_proba(X_test)[:, 1]
pred_nc1 = (np.array(pred_nc1) >= 0.5).astype(int)

f1_score(y_test, pred_nc1)

0.6080508474576272

In [ ]:
model_nc = RandomForestClassifier(
    random_state=42,
    class_weight='balanced',
    max_depth=8,
    min_samples_split=9,
    n_estimators=100,
)

model_nc.fit(X_nc, y_nc)
pred_nc = model_nc.predict_proba(X_test)[:, 1]
pred_nc = (np.array(pred_nc) >= 0.5).astype(int)

f1_score(y_test, pred_nc)

0.610738255033557