In [258]:
import pandas as pd
import numpy as np

In [259]:
df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")
df = df.drop('customerID', axis=1)
df.shape

(7043, 20)

In [260]:
df = df.dropna()

cols = df.select_dtypes(include='object').columns

mask = df[cols].apply(lambda col: col.astype(str).str.strip().eq('')).any(axis=1)

df = df[~mask]

C:\Users\User\AppData\Local\Temp\ipykernel_12096\3837072177.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cols = df.select_dtypes(include='object').columns

In [261]:
df.shape

(7032, 20)

In [262]:
df['TotalCharges'] = df['TotalCharges'].astype(float)
categorical_cols = df.select_dtypes(include='object').columns.tolist()
if 'Churn' in categorical_cols:
    categorical_cols.remove('Churn')


X = df.drop('Churn', axis=1).copy()
y = (df['Churn']).copy()
X = pd.get_dummies(X, columns=categorical_cols, drop_first=True)

C:\Users\User\AppData\Local\Temp\ipykernel_12096\245753736.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include='object').columns.tolist()

In [263]:
X.shape

(7032, 30)

In [264]:
X = X.astype(float)

In [265]:
X.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0.0,1.0,29.85,29.85,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,0.0,34.0,56.95,1889.50,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,0.0,2.0,53.85,108.15,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,0.0,45.0,42.30,1840.75,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0.0,2.0,70.70,151.65,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [266]:
from sklearn.preprocessing import LabelEncoder

enc = LabelEncoder()
y = enc.fit_transform(y)

In [267]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

for col in X.columns:
    if X[col].max() > 3:
        st = StandardScaler()
        X[col] = st.fit_transform(X[[col]])

In [268]:
X.shape

(7032, 30)

In [269]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test =train_test_split(
    X,y,
    random_state=42,
    test_size=0.2,
    shuffle=True,
    stratify=y
)

In [270]:
X_train.shape

(5625, 30)

In [271]:
c = 0
for i in y_train:
    if i == 1:
        c += 1

c

1495

In [272]:
from sklearn.dummy import DummyClassifier
from sklearn.metrics import f1_score, recall_score, precision_score

dummy = DummyClassifier()

dummy.fit(X_train, y_train)
p = dummy.predict(X_test)

f1_score(y_test, p)

0.0

In [273]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    class_weight='balanced',
    random_state=42
)
model.fit(X_train, y_train)
pred = model.predict(X_test)

pred = (np.array(pred) >= 0.4).astype(int)

print('logreg')
f1_score(y_test, pred)

logreg

0.6061224489795919

In [274]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_smote, y_smote = smote.fit_resample(X_train, y_train)

model1 = LogisticRegression(
    class_weight='balanced',
    random_state=42
)
model1.fit(X_smote, y_smote)
pred1 = model1.predict_proba(X_test)[:, 1]

pred1 = (np.array(pred1) >= 0.4).astype(int)

print('logreg_smote')
f1_score(y_test, pred1)

logreg_smote

0.6007462686567164

In [275]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    random_state=42,
    class_weight='balanced',
    max_depth=8,
    min_samples_split=9,
    n_estimators=100,
    )


rf.fit(X_train, y_train)

pred2 = rf.predict_proba(X_test)[:, 1]

pred2 = (np.array(pred2) >= 0.5).astype(int)

print('fr')
f1_score(y_test, pred2)

fr

0.6187961985216474

In [276]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    random_state=42,
    class_weight='balanced',
    max_depth=6,
    n_estimators=1000,
    min_samples_split=5,
    )

rf.fit(X_smote, y_smote)

pred3 = rf.predict(X_test)

print('fr_smote')
f1_score(y_test, pred3)

fr_smote

0.6310160427807486

In [277]:
from catboost import CatBoostClassifier


model3 = CatBoostClassifier(
    random_seed=42,
    learning_rate=0.01,
    loss_function='Logloss',
    eval_metric='F1',
    iterations=2000,
    depth=4,
    l2_leaf_reg=100
    )

model3.fit(X_train, y_train)
pred4 = model3.predict_proba(X_test)[:, 1]


pred4 = (np.array(pred4) >= 0.4).astype(int)
f1_score(y_test, pred4)

0:	learn: 0.5263158	total: 2.31ms	remaining: 4.62s
1:	learn: 0.5088908	total: 4.46ms	remaining: 4.46s
2:	learn: 0.5182452	total: 6.65ms	remaining: 4.42s
3:	learn: 0.5161826	total: 8.81ms	remaining: 4.4s
4:	learn: 0.5161826	total: 11.6ms	remaining: 4.62s
5:	learn: 0.4972091	total: 13.9ms	remaining: 4.6s
6:	learn: 0.5084459	total: 16ms	remaining: 4.56s
7:	learn: 0.4972091	total: 18.1ms	remaining: 4.51s
8:	learn: 0.4972091	total: 20.3ms	remaining: 4.49s
9:	learn: 0.5052989	total: 22.6ms	remaining: 4.49s
10:	learn: 0.5052989	total: 24.7ms	remaining: 4.46s
11:	learn: 0.5059322	total: 26.9ms	remaining: 4.46s
12:	learn: 0.5124106	total: 29.3ms	remaining: 4.48s
13:	learn: 0.5101351	total: 31.5ms	remaining: 4.47s
14:	learn: 0.5088608	total: 33.7ms	remaining: 4.46s
15:	learn: 0.5080169	total: 36ms	remaining: 4.47s
16:	learn: 0.5065650	total: 38.3ms	remaining: 4.47s
17:	learn: 0.5044586	total: 40.5ms	remaining: 4.46s
18:	learn: 0.5046809	total: 42.7ms	remaining: 4.45s
19:	learn: 0.5021386	total: 45ms	remaining: 4.46s
20:	learn: 0.5027742	total: 47.3ms	remaining: 4.46s
21:	learn: 0.5021349	total: 49.6ms	remaining: 4.46s
22:	learn: 0.5019239	total: 51.8ms	remaining: 4.45s
23:	learn: 0.5021349	total: 53.9ms	remaining: 4.44s
24:	learn: 0.5008562	total: 56.1ms	remaining: 4.43s
25:	learn: 0.5006418	total: 58.7ms	remaining: 4.46s
26:	learn: 0.4989303	total: 61ms	remaining: 4.46s
27:	learn: 0.4991438	total: 63.3ms	remaining: 4.45s
28:	learn: 0.5038363	total: 65.5ms	remaining: 4.45s
29:	learn: 0.4993565	total: 67.7ms	remaining: 4.44s
30:	learn: 0.4969957	total: 69.9ms	remaining: 4.44s
31:	learn: 0.4956971	total: 72.1ms	remaining: 4.43s
32:	learn: 0.4948097	total: 74.3ms	remaining: 4.43s
33:	learn: 0.4956897	total: 76.9ms	remaining: 4.45s
34:	learn: 0.4897782	total: 79.2ms	remaining: 4.45s
35:	learn: 0.4897782	total: 81.5ms	remaining: 4.44s
36:	learn: 0.4915475	total: 83.7ms	remaining: 4.44s
37:	learn: 0.4939446	total: 85.8ms	remaining: 4.43s
38:	learn: 0.4971995	total: 88.2ms	remaining: 4.43s
39:	learn: 0.4932929	total: 90.7ms	remaining: 4.45s
40:	learn: 0.4930796	total: 93.2ms	remaining: 4.45s
41:	learn: 0.4902216	total: 95.5ms	remaining: 4.45s
42:	learn: 0.4910908	total: 97.7ms	remaining: 4.45s
43:	learn: 0.4906481	total: 99.9ms	remaining: 4.44s
44:	learn: 0.4904348	total: 102ms	remaining: 4.44s
45:	learn: 0.4908616	total: 104ms	remaining: 4.43s
46:	learn: 0.4939236	total: 107ms	remaining: 4.46s
47:	learn: 0.4915181	total: 110ms	remaining: 4.47s
48:	learn: 0.4976242	total: 112ms	remaining: 4.47s
49:	learn: 0.4943625	total: 115ms	remaining: 4.47s
50:	learn: 0.4945770	total: 117ms	remaining: 4.47s
51:	learn: 0.5040790	total: 119ms	remaining: 4.46s
52:	learn: 0.5055698	total: 122ms	remaining: 4.46s
53:	learn: 0.5002152	total: 124ms	remaining: 4.47s
54:	learn: 0.5074882	total: 127ms	remaining: 4.47s
55:	learn: 0.5049208	total: 129ms	remaining: 4.47s
56:	learn: 0.5064157	total: 131ms	remaining: 4.46s
57:	learn: 0.5055698	total: 133ms	remaining: 4.46s
58:	learn: 0.5064267	total: 135ms	remaining: 4.46s
59:	learn: 0.5032147	total: 138ms	remaining: 4.47s
60:	learn: 0.5093857	total: 141ms	remaining: 4.47s
61:	learn: 0.5127551	total: 143ms	remaining: 4.47s
62:	learn: 0.5133872	total: 145ms	remaining: 4.46s
63:	learn: 0.5142371	total: 147ms	remaining: 4.46s
64:	learn: 0.5162928	total: 150ms	remaining: 4.45s
65:	learn: 0.5162928	total: 152ms	remaining: 4.45s
66:	learn: 0.5150106	total: 154ms	remaining: 4.45s
67:	learn: 0.5164835	total: 157ms	remaining: 4.45s
68:	learn: 0.5164280	total: 159ms	remaining: 4.45s
69:	learn: 0.5168350	total: 161ms	remaining: 4.44s
70:	learn: 0.5168634	total: 163ms	remaining: 4.44s
71:	learn: 0.5172704	total: 165ms	remaining: 4.43s
72:	learn: 0.5181129	total: 169ms	remaining: 4.45s
73:	learn: 0.5178947	total: 171ms	remaining: 4.46s
74:	learn: 0.5195460	total: 174ms	remaining: 4.46s
75:	learn: 0.5185185	total: 176ms	remaining: 4.45s
76:	learn: 0.5178646	total: 178ms	remaining: 4.46s
77:	learn: 0.5187053	total: 181ms	remaining: 4.46s
78:	learn: 0.5184874	total: 183ms	remaining: 4.46s
79:	learn: 0.5184874	total: 186ms	remaining: 4.46s
80:	learn: 0.5182696	total: 188ms	remaining: 4.46s
81:	learn: 0.5189235	total: 190ms	remaining: 4.45s
82:	learn: 0.5191096	total: 193ms	remaining: 4.45s
83:	learn: 0.5184874	total: 195ms	remaining: 4.44s
84:	learn: 0.5184874	total: 197ms	remaining: 4.44s
85:	learn: 0.5187053	total: 200ms	remaining: 4.46s
86:	learn: 0.5191096	total: 203ms	remaining: 4.46s
87:	learn: 0.5205709	total: 205ms	remaining: 4.46s
88:	learn: 0.5203525	total: 208ms	remaining: 4.46s
89:	learn: 0.5201342	total: 211ms	remaining: 4.47s
90:	learn: 0.5209732	total: 213ms	remaining: 4.47s
91:	learn: 0.5213747	total: 217ms	remaining: 4.5s
92:	learn: 0.5203525	total: 219ms	remaining: 4.5s
93:	learn: 0.5232315	total: 222ms	remaining: 4.49s
94:	learn: 0.5211563	total: 224ms	remaining: 4.5s
95:	learn: 0.5231926	total: 227ms	remaining: 4.5s
96:	learn: 0.5231926	total: 229ms	remaining: 4.5s
97:	learn: 0.5240284	total: 233ms	remaining: 4.52s
98:	learn: 0.5234114	total: 235ms	remaining: 4.52s
99:	learn: 0.5221757	total: 238ms	remaining: 4.51s
100:	learn: 0.5223943	total: 240ms	remaining: 4.52s
101:	learn: 0.5234506	total: 243ms	remaining: 4.51s
102:	learn: 0.5244668	total: 245ms	remaining: 4.51s
103:	learn: 0.5246449	total: 248ms	remaining: 4.52s
104:	learn: 0.5267112	total: 250ms	remaining: 4.51s
105:	learn: 0.5264914	total: 252ms	remaining: 4.51s
106:	learn: 0.5271059	total: 255ms	remaining: 4.51s
107:	learn: 0.5277199	total: 257ms	remaining: 4.5s
108:	learn: 0.5272803	total: 259ms	remaining: 4.5s
109:	learn: 0.5270608	total: 262ms	remaining: 4.49s
110:	learn: 0.5270608	total: 264ms	remaining: 4.5s
111:	learn: 0.5271059	total: 267ms	remaining: 4.49s
112:	learn: 0.5277199	total: 269ms	remaining: 4.49s
113:	learn: 0.5275000	total: 271ms	remaining: 4.49s
114:	learn: 0.5275000	total: 273ms	remaining: 4.48s
115:	learn: 0.5266667	total: 276ms	remaining: 4.48s
116:	learn: 0.5270608	total: 278ms	remaining: 4.47s
117:	learn: 0.5270608	total: 281ms	remaining: 4.47s
118:	learn: 0.5276737	total: 283ms	remaining: 4.47s
119:	learn: 0.5274542	total: 285ms	remaining: 4.47s
120:	learn: 0.5278470	total: 287ms	remaining: 4.46s
121:	learn: 0.5278470	total: 290ms	remaining: 4.46s
122:	learn: 0.5284587	total: 292ms	remaining: 4.45s
123:	learn: 0.5284587	total: 294ms	remaining: 4.45s
124:	learn: 0.5286783	total: 297ms	remaining: 4.45s
125:	learn: 0.5286783	total: 299ms	remaining: 4.45s
126:	learn: 0.5288981	total: 301ms	remaining: 4.44s
127:	learn: 0.5291181	total: 303ms	remaining: 4.43s
128:	learn: 0.5301205	total: 305ms	remaining: 4.43s
129:	learn: 0.5299003	total: 308ms	remaining: 4.42s
130:	learn: 0.5295096	total: 310ms	remaining: 4.42s
131:	learn: 0.5297297	total: 312ms	remaining: 4.42s
132:	learn: 0.5295096	total: 314ms	remaining: 4.41s
133:	learn: 0.5288981	total: 317ms	remaining: 4.41s
134:	learn: 0.5285060	total: 319ms	remaining: 4.41s
135:	learn: 0.5286783	total: 321ms	remaining: 4.4s
136:	learn: 0.5288981	total: 323ms	remaining: 4.39s
137:	learn: 0.5281133	total: 325ms	remaining: 4.39s
138:	learn: 0.5285060	total: 328ms	remaining: 4.39s
139:	learn: 0.5287261	total: 330ms	remaining: 4.38s
140:	learn: 0.5287261	total: 332ms	remaining: 4.38s
141:	learn: 0.5287261	total: 334ms	remaining: 4.38s
142:	learn: 0.5287261	total: 337ms	remaining: 4.37s
143:	learn: 0.5291181	total: 339ms	remaining: 4.37s
144:	learn: 0.5299501	total: 341ms	remaining: 4.36s
145:	learn: 0.5305613	total: 343ms	remaining: 4.36s
146:	learn: 0.5299501	total: 346ms	remaining: 4.36s
147:	learn: 0.5305613	total: 348ms	remaining: 4.35s
148:	learn: 0.5311721	total: 350ms	remaining: 4.35s
149:	learn: 0.5317823	total: 352ms	remaining: 4.34s
150:	learn: 0.5311721	total: 354ms	remaining: 4.33s
151:	learn: 0.5315615	total: 356ms	remaining: 4.33s
152:	learn: 0.5313408	total: 359ms	remaining: 4.33s
153:	learn: 0.5319502	total: 361ms	remaining: 4.33s
154:	learn: 0.5315091	total: 363ms	remaining: 4.32s
155:	learn: 0.5312889	total: 365ms	remaining: 4.32s
156:	learn: 0.5308489	total: 368ms	remaining: 4.31s
157:	learn: 0.5308489	total: 370ms	remaining: 4.31s
158:	learn: 0.5308489	total: 374ms	remaining: 4.33s
159:	learn: 0.5308489	total: 376ms	remaining: 4.33s
160:	learn: 0.5308489	total: 378ms	remaining: 4.32s
161:	learn: 0.5308489	total: 380ms	remaining: 4.32s
162:	learn: 0.5308489	total: 383ms	remaining: 4.31s
163:	learn: 0.5308489	total: 385ms	remaining: 4.31s
164:	learn: 0.5306291	total: 388ms	remaining: 4.31s
165:	learn: 0.5310174	total: 390ms	remaining: 4.31s
166:	learn: 0.5310174	total: 393ms	remaining: 4.31s
167:	learn: 0.5316246	total: 395ms	remaining: 4.31s
168:	learn: 0.5307979	total: 397ms	remaining: 4.3s
169:	learn: 0.5316246	total: 399ms	remaining: 4.3s
170:	learn: 0.5320116	total: 402ms	remaining: 4.3s
171:	learn: 0.5326177	total: 405ms	remaining: 4.31s
172:	learn: 0.5323979	total: 408ms	remaining: 4.3s
173:	learn: 0.5323979	total: 410ms	remaining: 4.3s
174:	learn: 0.5326177	total: 412ms	remaining: 4.3s
175:	learn: 0.5323979	total: 415ms	remaining: 4.3s
176:	learn: 0.5323979	total: 417ms	remaining: 4.29s
177:	learn: 0.5323979	total: 419ms	remaining: 4.29s
178:	learn: 0.5315724	total: 422ms	remaining: 4.29s
179:	learn: 0.5330033	total: 424ms	remaining: 4.29s
180:	learn: 0.5327835	total: 426ms	remaining: 4.28s
181:	learn: 0.5330033	total: 428ms	remaining: 4.28s
182:	learn: 0.5323979	total: 430ms	remaining: 4.27s
183:	learn: 0.5327835	total: 433ms	remaining: 4.27s
184:	learn: 0.5333883	total: 435ms	remaining: 4.26s
185:	learn: 0.5358025	total: 437ms	remaining: 4.26s
186:	learn: 0.5353618	total: 439ms	remaining: 4.26s
187:	learn: 0.5359638	total: 442ms	remaining: 4.26s
188:	learn: 0.5345395	total: 444ms	remaining: 4.25s
189:	learn: 0.5357436	total: 446ms	remaining: 4.25s
190:	learn: 0.5353038	total: 448ms	remaining: 4.24s
191:	learn: 0.5361248	total: 451ms	remaining: 4.25s
192:	learn: 0.5361248	total: 453ms	remaining: 4.25s
193:	learn: 0.5371054	total: 456ms	remaining: 4.24s
194:	learn: 0.5373257	total: 458ms	remaining: 4.24s
195:	learn: 0.5383040	total: 460ms	remaining: 4.24s
196:	learn: 0.5400982	total: 463ms	remaining: 4.23s
197:	learn: 0.5400982	total: 465ms	remaining: 4.23s
198:	learn: 0.5395006	total: 468ms	remaining: 4.24s
199:	learn: 0.5395006	total: 471ms	remaining: 4.23s
200:	learn: 0.5389025	total: 473ms	remaining: 4.23s
201:	learn: 0.5400982	total: 475ms	remaining: 4.23s
202:	learn: 0.5403193	total: 477ms	remaining: 4.23s
203:	learn: 0.5406953	total: 480ms	remaining: 4.22s
204:	learn: 0.5406953	total: 483ms	remaining: 4.22s
205:	learn: 0.5420408	total: 485ms	remaining: 4.22s
206:	learn: 0.5412245	total: 488ms	remaining: 4.23s
207:	learn: 0.5414455	total: 491ms	remaining: 4.23s
208:	learn: 0.5420408	total: 493ms	remaining: 4.22s
209:	learn: 0.5420408	total: 496ms	remaining: 4.22s
210:	learn: 0.5428571	total: 499ms	remaining: 4.23s
211:	learn: 0.5422621	total: 502ms	remaining: 4.23s
212:	learn: 0.5424144	total: 504ms	remaining: 4.23s
213:	learn: 0.5432300	total: 507ms	remaining: 4.23s
214:	learn: 0.5424144	total: 509ms	remaining: 4.23s
215:	learn: 0.5444173	total: 512ms	remaining: 4.23s
216:	learn: 0.5450102	total: 515ms	remaining: 4.23s
217:	learn: 0.5456026	total: 518ms	remaining: 4.24s
218:	learn: 0.5456026	total: 521ms	remaining: 4.23s
219:	learn: 0.5461945	total: 523ms	remaining: 4.23s
220:	learn: 0.5467860	total: 526ms	remaining: 4.23s
221:	learn: 0.5465636	total: 528ms	remaining: 4.23s
222:	learn: 0.5473770	total: 532ms	remaining: 4.24s
223:	learn: 0.5463415	total: 535ms	remaining: 4.24s
224:	learn: 0.5475223	total: 537ms	remaining: 4.24s
225:	learn: 0.5487013	total: 539ms	remaining: 4.23s
226:	learn: 0.5484787	total: 542ms	remaining: 4.23s
227:	learn: 0.5496555	total: 546ms	remaining: 4.24s
228:	learn: 0.5488448	total: 549ms	remaining: 4.24s
229:	learn: 0.5488448	total: 551ms	remaining: 4.24s
230:	learn: 0.5509464	total: 554ms	remaining: 4.24s
231:	learn: 0.5509464	total: 556ms	remaining: 4.24s
232:	learn: 0.5519742	total: 559ms	remaining: 4.24s
233:	learn: 0.5515298	total: 563ms	remaining: 4.25s
234:	learn: 0.5523349	total: 566ms	remaining: 4.25s
235:	learn: 0.5529175	total: 568ms	remaining: 4.25s
236:	learn: 0.5526951	total: 571ms	remaining: 4.25s
237:	learn: 0.5529175	total: 573ms	remaining: 4.24s
238:	learn: 0.5528325	total: 577ms	remaining: 4.25s
239:	learn: 0.5528325	total: 580ms	remaining: 4.25s
240:	learn: 0.5534996	total: 583ms	remaining: 4.25s
241:	learn: 0.5530547	total: 585ms	remaining: 4.25s
242:	learn: 0.5542169	total: 587ms	remaining: 4.25s
243:	learn: 0.5545746	total: 592ms	remaining: 4.26s
244:	learn: 0.5553772	total: 595ms	remaining: 4.26s
245:	learn: 0.5555110	total: 597ms	remaining: 4.26s
246:	learn: 0.5572458	total: 600ms	remaining: 4.26s
247:	learn: 0.5576923	total: 602ms	remaining: 4.25s
248:	learn: 0.5572458	total: 605ms	remaining: 4.25s
249:	learn: 0.5574690	total: 607ms	remaining: 4.25s
250:	learn: 0.5585298	total: 610ms	remaining: 4.25s
251:	learn: 0.5576000	total: 613ms	remaining: 4.25s
252:	learn: 0.5570228	total: 615ms	remaining: 4.25s
253:	learn: 0.5581767	total: 618ms	remaining: 4.25s
254:	learn: 0.5591054	total: 620ms	remaining: 4.24s
255:	learn: 0.5585298	total: 623ms	remaining: 4.25s
256:	learn: 0.5591054	total: 626ms	remaining: 4.24s
257:	learn: 0.5594573	total: 628ms	remaining: 4.24s
258:	learn: 0.5598086	total: 630ms	remaining: 4.24s
259:	learn: 0.5609562	total: 633ms	remaining: 4.23s
260:	learn: 0.5609562	total: 635ms	remaining: 4.23s
261:	learn: 0.5598086	total: 637ms	remaining: 4.22s
262:	learn: 0.5595855	total: 639ms	remaining: 4.22s
263:	learn: 0.5598086	total: 642ms	remaining: 4.22s
264:	learn: 0.5598086	total: 644ms	remaining: 4.21s
265:	learn: 0.5609562	total: 646ms	remaining: 4.21s
266:	learn: 0.5607328	total: 648ms	remaining: 4.21s
267:	learn: 0.5613057	total: 651ms	remaining: 4.21s
268:	learn: 0.5614314	total: 654ms	remaining: 4.21s
269:	learn: 0.5620032	total: 657ms	remaining: 4.21s
270:	learn: 0.5620032	total: 659ms	remaining: 4.2s
271:	learn: 0.5622266	total: 661ms	remaining: 4.2s
272:	learn: 0.5622266	total: 664ms	remaining: 4.2s
273:	learn: 0.5627981	total: 666ms	remaining: 4.19s
274:	learn: 0.5627981	total: 668ms	remaining: 4.19s
275:	learn: 0.5625745	total: 671ms	remaining: 4.19s
276:	learn: 0.5625745	total: 673ms	remaining: 4.19s
277:	learn: 0.5629218	total: 676ms	remaining: 4.19s
278:	learn: 0.5623511	total: 678ms	remaining: 4.18s
279:	learn: 0.5623511	total: 681ms	remaining: 4.18s
280:	learn: 0.5629218	total: 683ms	remaining: 4.18s
281:	learn: 0.5629218	total: 685ms	remaining: 4.17s
282:	learn: 0.5629218	total: 688ms	remaining: 4.17s
283:	learn: 0.5629218	total: 691ms	remaining: 4.17s
284:	learn: 0.5626984	total: 693ms	remaining: 4.17s
285:	learn: 0.5629218	total: 696ms	remaining: 4.17s
286:	learn: 0.5626984	total: 698ms	remaining: 4.17s
287:	learn: 0.5631454	total: 700ms	remaining: 4.16s
288:	learn: 0.5634921	total: 703ms	remaining: 4.16s
289:	learn: 0.5637158	total: 705ms	remaining: 4.16s
290:	learn: 0.5638382	total: 707ms	remaining: 4.15s
291:	learn: 0.5632685	total: 709ms	remaining: 4.15s
292:	learn: 0.5632685	total: 711ms	remaining: 4.14s
293:	learn: 0.5634921	total: 713ms	remaining: 4.14s
294:	learn: 0.5646312	total: 716ms	remaining: 4.13s
295:	learn: 0.5644075	total: 718ms	remaining: 4.13s
296:	learn: 0.5639604	total: 720ms	remaining: 4.13s
297:	learn: 0.5644075	total: 722ms	remaining: 4.13s
298:	learn: 0.5644075	total: 725ms	remaining: 4.12s
299:	learn: 0.5639604	total: 727ms	remaining: 4.12s
300:	learn: 0.5650970	total: 729ms	remaining: 4.11s
301:	learn: 0.5645289	total: 731ms	remaining: 4.11s
302:	learn: 0.5654409	total: 733ms	remaining: 4.11s
303:	learn: 0.5657843	total: 736ms	remaining: 4.1s
304:	learn: 0.5660079	total: 738ms	remaining: 4.1s
305:	learn: 0.5665745	total: 740ms	remaining: 4.1s
306:	learn: 0.5677063	total: 742ms	remaining: 4.09s
307:	learn: 0.5677063	total: 744ms	remaining: 4.09s
308:	learn: 0.5684959	total: 746ms	remaining: 4.08s
309:	learn: 0.5687204	total: 749ms	remaining: 4.08s
310:	learn: 0.5679305	total: 751ms	remaining: 4.08s
311:	learn: 0.5690608	total: 753ms	remaining: 4.07s
312:	learn: 0.5677063	total: 755ms	remaining: 4.07s
313:	learn: 0.5679305	total: 757ms	remaining: 4.07s
314:	learn: 0.5679305	total: 760ms	remaining: 4.06s
315:	learn: 0.5679305	total: 762ms	remaining: 4.06s
316:	learn: 0.5679305	total: 764ms	remaining: 4.05s
317:	learn: 0.5682715	total: 766ms	remaining: 4.05s
318:	learn: 0.5682715	total: 769ms	remaining: 4.05s
319:	learn: 0.5697400	total: 771ms	remaining: 4.05s
320:	learn: 0.5700787	total: 773ms	remaining: 4.04s
321:	learn: 0.5701893	total: 775ms	remaining: 4.04s
322:	learn: 0.5699645	total: 777ms	remaining: 4.04s
323:	learn: 0.5699645	total: 780ms	remaining: 4.03s
324:	learn: 0.5705280	total: 782ms	remaining: 4.03s
325:	learn: 0.5710910	total: 784ms	remaining: 4.03s
326:	learn: 0.5713163	total: 786ms	remaining: 4.02s
327:	learn: 0.5709792	total: 789ms	remaining: 4.02s
328:	learn: 0.5713163	total: 791ms	remaining: 4.01s
329:	learn: 0.5708661	total: 793ms	remaining: 4.01s
330:	learn: 0.5705280	total: 796ms	remaining: 4.01s
331:	learn: 0.5714286	total: 798ms	remaining: 4.01s
332:	learn: 0.5708661	total: 801ms	remaining: 4.01s
333:	learn: 0.5709792	total: 803ms	remaining: 4s
334:	learn: 0.5712038	total: 805ms	remaining: 4s
335:	learn: 0.5717656	total: 807ms	remaining: 4s
336:	learn: 0.5712038	total: 809ms	remaining: 3.99s
337:	learn: 0.5716535	total: 812ms	remaining: 3.99s
338:	learn: 0.5716535	total: 814ms	remaining: 3.99s
339:	learn: 0.5723270	total: 816ms	remaining: 3.98s
340:	learn: 0.5723270	total: 819ms	remaining: 3.98s
341:	learn: 0.5728880	total: 821ms	remaining: 3.98s
342:	learn: 0.5740086	total: 823ms	remaining: 3.98s
343:	learn: 0.5740086	total: 825ms	remaining: 3.97s
344:	learn: 0.5740086	total: 827ms	remaining: 3.97s
345:	learn: 0.5741176	total: 830ms	remaining: 3.96s
346:	learn: 0.5737834	total: 832ms	remaining: 3.96s
347:	learn: 0.5734485	total: 834ms	remaining: 3.96s
348:	learn: 0.5737834	total: 836ms	remaining: 3.96s
349:	learn: 0.5743429	total: 838ms	remaining: 3.95s
350:	learn: 0.5743429	total: 840ms	remaining: 3.95s
351:	learn: 0.5745683	total: 843ms	remaining: 3.94s
352:	learn: 0.5745683	total: 845ms	remaining: 3.94s
353:	learn: 0.5740086	total: 847ms	remaining: 3.94s
354:	learn: 0.5740086	total: 849ms	remaining: 3.94s
355:	learn: 0.5751275	total: 851ms	remaining: 3.93s
356:	learn: 0.5749020	total: 854ms	remaining: 3.93s
357:	learn: 0.5763508	total: 856ms	remaining: 3.92s
358:	learn: 0.5763508	total: 858ms	remaining: 3.92s
359:	learn: 0.5769080	total: 860ms	remaining: 3.92s
360:	learn: 0.5761252	total: 862ms	remaining: 3.92s
361:	learn: 0.5761252	total: 865ms	remaining: 3.91s
362:	learn: 0.5766823	total: 867ms	remaining: 3.91s
363:	learn: 0.5770133	total: 869ms	remaining: 3.9s
364:	learn: 0.5772390	total: 871ms	remaining: 3.9s
365:	learn: 0.5778993	total: 873ms	remaining: 3.9s
366:	learn: 0.5778993	total: 876ms	remaining: 3.9s
367:	learn: 0.5778993	total: 878ms	remaining: 3.89s
368:	learn: 0.5782286	total: 880ms	remaining: 3.89s
369:	learn: 0.5782286	total: 883ms	remaining: 3.89s
370:	learn: 0.5771183	total: 885ms	remaining: 3.88s
371:	learn: 0.5781250	total: 887ms	remaining: 3.88s
372:	learn: 0.5784543	total: 889ms	remaining: 3.88s
373:	learn: 0.5787832	total: 891ms	remaining: 3.88s
374:	learn: 0.5782286	total: 894ms	remaining: 3.87s
375:	learn: 0.5787832	total: 896ms	remaining: 3.87s
376:	learn: 0.5793372	total: 898ms	remaining: 3.87s
377:	learn: 0.5804441	total: 900ms	remaining: 3.86s
378:	learn: 0.5802181	total: 902ms	remaining: 3.86s
379:	learn: 0.5804441	total: 904ms	remaining: 3.85s
380:	learn: 0.5798909	total: 906ms	remaining: 3.85s
381:	learn: 0.5796650	total: 909ms	remaining: 3.85s
382:	learn: 0.5794393	total: 911ms	remaining: 3.85s
383:	learn: 0.5799922	total: 913ms	remaining: 3.84s
384:	learn: 0.5797665	total: 915ms	remaining: 3.84s
385:	learn: 0.5799922	total: 917ms	remaining: 3.83s

0.6148055207026348

In [278]:
X.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0.0,-1.280248,-1.161694,-0.994194,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,0.0,0.064303,-0.260878,-0.173740,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,0.0,-1.239504,-0.363923,-0.959649,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,0.0,0.512486,-0.747850,-0.195248,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,0.0,-1.239504,0.196178,-0.940457,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [279]:
cat_fet = X.columns

fet_idx = np.arange(len(cat_fet))
fet_idx = np.delete( fet_idx, [4, 17, 18])

In [280]:
fet_idx

array([ 0,  1,  2,  3,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [281]:
from imblearn.over_sampling import SMOTENC

nc = SMOTENC(categorical_features = fet_idx.tolist(), random_state= 42)

X_nc, y_nc = nc.fit_resample(X_train, y_train)

In [282]:
model_nc1 = LogisticRegression(
    random_state=42,
    class_weight='balanced',
)

model_nc1.fit(X_nc, y_nc)
pred_nc1 = model_nc1.predict_proba(X_test)[:, 1]
pred_nc1 = (np.array(pred_nc1) >= 0.5).astype(int)

f1_score(y_test, pred_nc1)

0.6048565121412803

In [283]:
model_nc = RandomForestClassifier(
    random_state=42,
    class_weight='balanced',
    max_depth=8,
    min_samples_split=9,
    n_estimators=100,
)

model_nc.fit(X_nc, y_nc)
pred_nc = model_nc.predict_proba(X_test)[:, 1]
pred_nc = (np.array(pred_nc) >= 0.5).astype(int)

f1_score(y_test, pred_nc)

0.6326530612244898

In [287]:
from catboost import CatBoostClassifier


model_nc = CatBoostClassifier(
    random_seed=42,
    learning_rate=0.01,
    loss_function='Logloss',
    eval_metric='F1',
    iterations=2000,
    depth=4,
    l2_leaf_reg=100,
    )

model_nc.fit(X_nc, y_nc)
pred_nc = model_nc.predict_proba(X_test)[:, 1]
pred_nc = (np.array(pred_nc) >= 0.5).astype(int)

f1_score(y_test, pred_nc)

0:	learn: 0.8036957	total: 2.92ms	remaining: 5.83s
1:	learn: 0.7949402	total: 6.04ms	remaining: 6.03s
2:	learn: 0.7916416	total: 8.66ms	remaining: 5.76s
3:	learn: 0.8018766	total: 11.3ms	remaining: 5.62s
4:	learn: 0.8094331	total: 14.5ms	remaining: 5.79s
5:	learn: 0.8101970	total: 17.3ms	remaining: 5.74s
6:	learn: 0.8129529	total: 19.8ms	remaining: 5.64s
7:	learn: 0.8136590	total: 22.4ms	remaining: 5.57s
8:	learn: 0.8107370	total: 24.9ms	remaining: 5.51s
9:	learn: 0.8110326	total: 28.6ms	remaining: 5.7s
10:	learn: 0.8122500	total: 31.3ms	remaining: 5.66s
11:	learn: 0.8112210	total: 33.9ms	remaining: 5.62s
12:	learn: 0.8123499	total: 36.5ms	remaining: 5.58s
13:	learn: 0.8127217	total: 39.1ms	remaining: 5.54s
14:	learn: 0.8134816	total: 41.6ms	remaining: 5.51s
15:	learn: 0.8116571	total: 45.7ms	remaining: 5.66s
16:	learn: 0.8126861	total: 48.6ms	remaining: 5.67s
17:	learn: 0.8126861	total: 51.4ms	remaining: 5.66s
18:	learn: 0.8124070	total: 54ms	remaining: 5.63s
19:	learn: 0.8130305	total: 56.6ms	remaining: 5.6s
20:	learn: 0.8143547	total: 59.7ms	remaining: 5.63s
21:	learn: 0.8136531	total: 62.3ms	remaining: 5.6s
22:	learn: 0.8124855	total: 64.9ms	remaining: 5.57s
23:	learn: 0.8139562	total: 67.4ms	remaining: 5.55s
24:	learn: 0.8122685	total: 69.9ms	remaining: 5.53s
25:	learn: 0.8125722	total: 72.5ms	remaining: 5.5s
26:	learn: 0.8130701	total: 76.4ms	remaining: 5.58s
27:	learn: 0.8125361	total: 79.1ms	remaining: 5.57s
28:	learn: 0.8128898	total: 81.7ms	remaining: 5.55s
29:	learn: 0.8135750	total: 84.4ms	remaining: 5.54s
30:	learn: 0.8146016	total: 86.9ms	remaining: 5.52s
31:	learn: 0.8158288	total: 89.7ms	remaining: 5.51s
32:	learn: 0.8165708	total: 92.6ms	remaining: 5.52s
33:	learn: 0.8165148	total: 95.4ms	remaining: 5.51s
34:	learn: 0.8162231	total: 98ms	remaining: 5.5s
35:	learn: 0.8167684	total: 101ms	remaining: 5.5s
36:	learn: 0.8162137	total: 104ms	remaining: 5.49s
37:	learn: 0.8165001	total: 106ms	remaining: 5.49s
38:	learn: 0.8176362	total: 109ms	remaining: 5.49s
39:	learn: 0.8171521	total: 112ms	remaining: 5.49s
40:	learn: 0.8169112	total: 115ms	remaining: 5.47s
41:	learn: 0.8167418	total: 117ms	remaining: 5.46s
42:	learn: 0.8158260	total: 120ms	remaining: 5.46s
43:	learn: 0.8154130	total: 123ms	remaining: 5.45s
44:	learn: 0.8157379	total: 126ms	remaining: 5.46s
45:	learn: 0.8161238	total: 128ms	remaining: 5.45s
46:	learn: 0.8170183	total: 131ms	remaining: 5.44s
47:	learn: 0.8172911	total: 134ms	remaining: 5.43s
48:	learn: 0.8170605	total: 136ms	remaining: 5.42s
49:	learn: 0.8172911	total: 139ms	remaining: 5.42s
50:	learn: 0.8171125	total: 142ms	remaining: 5.42s
51:	learn: 0.8172788	total: 145ms	remaining: 5.41s
52:	learn: 0.8170802	total: 147ms	remaining: 5.41s
53:	learn: 0.8166609	total: 150ms	remaining: 5.4s
54:	learn: 0.8174255	total: 153ms	remaining: 5.4s
55:	learn: 0.8170154	total: 155ms	remaining: 5.4s
56:	learn: 0.8170252	total: 158ms	remaining: 5.39s
57:	learn: 0.8170252	total: 161ms	remaining: 5.39s
58:	learn: 0.8172988	total: 164ms	remaining: 5.39s
59:	learn: 0.8172466	total: 167ms	remaining: 5.39s
60:	learn: 0.8174255	total: 170ms	remaining: 5.39s
61:	learn: 0.8176566	total: 173ms	remaining: 5.4s
62:	learn: 0.8180243	total: 176ms	remaining: 5.41s
63:	learn: 0.8176987	total: 179ms	remaining: 5.42s
64:	learn: 0.8178877	total: 182ms	remaining: 5.42s
65:	learn: 0.8181608	total: 185ms	remaining: 5.42s
66:	learn: 0.8182239	total: 189ms	remaining: 5.45s
67:	learn: 0.8180030	total: 193ms	remaining: 5.47s
68:	learn: 0.8188121	total: 195ms	remaining: 5.47s
69:	learn: 0.8190212	total: 198ms	remaining: 5.46s
70:	learn: 0.8186122	total: 201ms	remaining: 5.46s
71:	learn: 0.8185489	total: 205ms	remaining: 5.5s
72:	learn: 0.8185489	total: 209ms	remaining: 5.51s
73:	learn: 0.8186540	total: 212ms	remaining: 5.5s
74:	learn: 0.8192632	total: 214ms	remaining: 5.5s
75:	learn: 0.8186229	total: 217ms	remaining: 5.5s
76:	learn: 0.8185391	total: 221ms	remaining: 5.53s
77:	learn: 0.8185810	total: 224ms	remaining: 5.53s
78:	learn: 0.8185596	total: 229ms	remaining: 5.56s
79:	learn: 0.8188322	total: 234ms	remaining: 5.61s
80:	learn: 0.8186014	total: 237ms	remaining: 5.62s
81:	learn: 0.8184232	total: 240ms	remaining: 5.62s
82:	learn: 0.8185917	total: 243ms	remaining: 5.62s
83:	learn: 0.8181713	total: 246ms	remaining: 5.62s
84:	learn: 0.8186229	total: 249ms	remaining: 5.61s
85:	learn: 0.8180663	total: 252ms	remaining: 5.62s
86:	learn: 0.8185810	total: 255ms	remaining: 5.61s
87:	learn: 0.8190322	total: 258ms	remaining: 5.61s
88:	learn: 0.8188958	total: 261ms	remaining: 5.6s
89:	learn: 0.8188012	total: 264ms	remaining: 5.59s
90:	learn: 0.8186756	total: 267ms	remaining: 5.6s
91:	learn: 0.8182765	total: 270ms	remaining: 5.6s
92:	learn: 0.8187811	total: 273ms	remaining: 5.59s
93:	learn: 0.8188339	total: 276ms	remaining: 5.59s
94:	learn: 0.8188758	total: 278ms	remaining: 5.58s
95:	learn: 0.8185605	total: 281ms	remaining: 5.58s
96:	learn: 0.8192130	total: 284ms	remaining: 5.58s
97:	learn: 0.8193078	total: 287ms	remaining: 5.57s
98:	learn: 0.8188028	total: 290ms	remaining: 5.56s
99:	learn: 0.8189505	total: 293ms	remaining: 5.56s
100:	learn: 0.8186769	total: 295ms	remaining: 5.55s
101:	learn: 0.8189505	total: 299ms	remaining: 5.56s
102:	learn: 0.8189086	total: 302ms	remaining: 5.56s
103:	learn: 0.8188137	total: 304ms	remaining: 5.55s
104:	learn: 0.8192352	total: 307ms	remaining: 5.54s
105:	learn: 0.8192883	total: 310ms	remaining: 5.54s
106:	learn: 0.8199003	total: 313ms	remaining: 5.54s
107:	learn: 0.8199420	total: 316ms	remaining: 5.54s
108:	learn: 0.8200255	total: 319ms	remaining: 5.53s
109:	learn: 0.8196569	total: 321ms	remaining: 5.52s
110:	learn: 0.8193833	total: 324ms	remaining: 5.52s
111:	learn: 0.8199003	total: 327ms	remaining: 5.52s
112:	learn: 0.8202273	total: 331ms	remaining: 5.53s
113:	learn: 0.8208159	total: 334ms	remaining: 5.53s
114:	learn: 0.8210063	total: 337ms	remaining: 5.52s
115:	learn: 0.8204712	total: 340ms	remaining: 5.51s
116:	learn: 0.8204712	total: 342ms	remaining: 5.51s
117:	learn: 0.8205961	total: 345ms	remaining: 5.5s
118:	learn: 0.8207865	total: 348ms	remaining: 5.5s
119:	learn: 0.8209232	total: 350ms	remaining: 5.49s
120:	learn: 0.8206793	total: 353ms	remaining: 5.48s
121:	learn: 0.8210600	total: 356ms	remaining: 5.47s
122:	learn: 0.8208280	total: 359ms	remaining: 5.47s
123:	learn: 0.8203760	total: 361ms	remaining: 5.47s
124:	learn: 0.8206913	total: 364ms	remaining: 5.46s
125:	learn: 0.8203760	total: 367ms	remaining: 5.46s
126:	learn: 0.8211967	total: 369ms	remaining: 5.45s
127:	learn: 0.8221344	total: 372ms	remaining: 5.44s
128:	learn: 0.8222713	total: 375ms	remaining: 5.43s
129:	learn: 0.8222171	total: 378ms	remaining: 5.43s
130:	learn: 0.8230366	total: 380ms	remaining: 5.42s
131:	learn: 0.8234610	total: 383ms	remaining: 5.42s
132:	learn: 0.8231736	total: 386ms	remaining: 5.41s
133:	learn: 0.8233651	total: 388ms	remaining: 5.41s
134:	learn: 0.8235979	total: 391ms	remaining: 5.4s
135:	learn: 0.8235568	total: 395ms	remaining: 5.41s
136:	learn: 0.8239814	total: 398ms	remaining: 5.41s
137:	learn: 0.8239814	total: 400ms	remaining: 5.4s
138:	learn: 0.8242142	total: 403ms	remaining: 5.4s
139:	learn: 0.8239814	total: 406ms	remaining: 5.39s
140:	learn: 0.8253229	total: 409ms	remaining: 5.39s
141:	learn: 0.8253636	total: 412ms	remaining: 5.38s
142:	learn: 0.8257884	total: 414ms	remaining: 5.38s
143:	learn: 0.8258290	total: 417ms	remaining: 5.38s
144:	learn: 0.8263097	total: 420ms	remaining: 5.37s
145:	learn: 0.8263501	total: 422ms	remaining: 5.36s
146:	learn: 0.8265425	total: 425ms	remaining: 5.36s
147:	learn: 0.8266946	total: 428ms	remaining: 5.36s
148:	learn: 0.8265425	total: 431ms	remaining: 5.35s
149:	learn: 0.8267350	total: 434ms	remaining: 5.35s
150:	learn: 0.8265425	total: 436ms	remaining: 5.34s
151:	learn: 0.8269119	total: 439ms	remaining: 5.34s
152:	learn: 0.8270642	total: 442ms	remaining: 5.34s
153:	learn: 0.8270081	total: 446ms	remaining: 5.34s
154:	learn: 0.8271605	total: 448ms	remaining: 5.33s
155:	learn: 0.8270642	total: 451ms	remaining: 5.33s
156:	learn: 0.8268469	total: 453ms	remaining: 5.32s
157:	learn: 0.8269029	total: 456ms	remaining: 5.32s
158:	learn: 0.8273692	total: 459ms	remaining: 5.32s
159:	learn: 0.8275862	total: 462ms	remaining: 5.32s
160:	learn: 0.8273532	total: 465ms	remaining: 5.31s
161:	learn: 0.8278593	total: 468ms	remaining: 5.31s
162:	learn: 0.8275460	total: 471ms	remaining: 5.3s
163:	learn: 0.8275058	total: 474ms	remaining: 5.3s
164:	learn: 0.8277389	total: 476ms	remaining: 5.3s
165:	learn: 0.8278354	total: 479ms	remaining: 5.29s
166:	learn: 0.8275058	total: 482ms	remaining: 5.29s
167:	learn: 0.8273692	total: 485ms	remaining: 5.28s
168:	learn: 0.8270799	total: 487ms	remaining: 5.28s
169:	learn: 0.8267909	total: 490ms	remaining: 5.28s
170:	learn: 0.8266542	total: 493ms	remaining: 5.28s
171:	learn: 0.8265330	total: 496ms	remaining: 5.27s
172:	learn: 0.8264366	total: 498ms	remaining: 5.26s
173:	learn: 0.8270957	total: 501ms	remaining: 5.26s
174:	learn: 0.8277551	total: 504ms	remaining: 5.25s
175:	learn: 0.8269993	total: 507ms	remaining: 5.25s
176:	learn: 0.8269590	total: 510ms	remaining: 5.25s
177:	learn: 0.8271922	total: 512ms	remaining: 5.24s
178:	learn: 0.8275621	total: 515ms	remaining: 5.24s
179:	learn: 0.8271922	total: 518ms	remaining: 5.24s
180:	learn: 0.8273289	total: 521ms	remaining: 5.23s
181:	learn: 0.8272325	total: 524ms	remaining: 5.23s
182:	learn: 0.8271360	total: 527ms	remaining: 5.23s
183:	learn: 0.8269836	total: 530ms	remaining: 5.23s
184:	learn: 0.8272568	total: 532ms	remaining: 5.22s
185:	learn: 0.8273692	total: 535ms	remaining: 5.22s
186:	learn: 0.8268872	total: 538ms	remaining: 5.22s
187:	learn: 0.8271202	total: 541ms	remaining: 5.21s
188:	learn: 0.8272166	total: 544ms	remaining: 5.21s
189:	learn: 0.8277791	total: 547ms	remaining: 5.21s
190:	learn: 0.8276425	total: 550ms	remaining: 5.21s
191:	learn: 0.8276023	total: 553ms	remaining: 5.21s
192:	learn: 0.8281815	total: 556ms	remaining: 5.2s
193:	learn: 0.8285281	total: 558ms	remaining: 5.2s
194:	learn: 0.8283582	total: 561ms	remaining: 5.19s
195:	learn: 0.8282216	total: 564ms	remaining: 5.19s
196:	learn: 0.8283582	total: 566ms	remaining: 5.18s
197:	learn: 0.8284714	total: 569ms	remaining: 5.18s
198:	learn: 0.8280612	total: 572ms	remaining: 5.18s
199:	learn: 0.8284314	total: 575ms	remaining: 5.17s
200:	learn: 0.8278918	total: 577ms	remaining: 5.17s
201:	learn: 0.8278918	total: 580ms	remaining: 5.16s
202:	learn: 0.8278516	total: 583ms	remaining: 5.16s
203:	learn: 0.8280448	total: 586ms	remaining: 5.16s
204:	learn: 0.8280448	total: 589ms	remaining: 5.15s
205:	learn: 0.8281250	total: 591ms	remaining: 5.15s
206:	learn: 0.8282216	total: 594ms	remaining: 5.14s
207:	learn: 0.8280849	total: 597ms	remaining: 5.14s
208:	learn: 0.8278918	total: 600ms	remaining: 5.14s
209:	learn: 0.8281651	total: 603ms	remaining: 5.14s
210:	learn: 0.8284548	total: 605ms	remaining: 5.13s
211:	learn: 0.8284548	total: 608ms	remaining: 5.13s
212:	learn: 0.8286880	total: 611ms	remaining: 5.12s
213:	learn: 0.8286481	total: 613ms	remaining: 5.12s
214:	learn: 0.8285514	total: 617ms	remaining: 5.12s
215:	learn: 0.8286880	total: 620ms	remaining: 5.12s
216:	learn: 0.8289213	total: 623ms	remaining: 5.12s
217:	learn: 0.8288246	total: 625ms	remaining: 5.11s
218:	learn: 0.8289612	total: 628ms	remaining: 5.11s
219:	learn: 0.8288246	total: 632ms	remaining: 5.11s
220:	learn: 0.8287280	total: 635ms	remaining: 5.11s
221:	learn: 0.8287448	total: 638ms	remaining: 5.11s
222:	learn: 0.8289213	total: 640ms	remaining: 5.1s
223:	learn: 0.8289612	total: 643ms	remaining: 5.1s
224:	learn: 0.8288246	total: 645ms	remaining: 5.09s
225:	learn: 0.8293308	total: 649ms	remaining: 5.09s
226:	learn: 0.8291944	total: 651ms	remaining: 5.09s
227:	learn: 0.8290180	total: 654ms	remaining: 5.08s
228:	learn: 0.8291147	total: 657ms	remaining: 5.08s
229:	learn: 0.8292114	total: 659ms	remaining: 5.07s
230:	learn: 0.8294447	total: 662ms	remaining: 5.07s
231:	learn: 0.8293081	total: 665ms	remaining: 5.07s
232:	learn: 0.8295415	total: 668ms	remaining: 5.06s
233:	learn: 0.8295017	total: 670ms	remaining: 5.06s
234:	learn: 0.8295415	total: 673ms	remaining: 5.06s
235:	learn: 0.8293081	total: 676ms	remaining: 5.05s
236:	learn: 0.8294049	total: 680ms	remaining: 5.06s
237:	learn: 0.8296383	total: 683ms	remaining: 5.05s
238:	learn: 0.8299288	total: 685ms	remaining: 5.05s
239:	learn: 0.8295985	total: 688ms	remaining: 5.05s
240:	learn: 0.8293081	total: 691ms	remaining: 5.04s
241:	learn: 0.8292114	total: 694ms	remaining: 5.04s
242:	learn: 0.8291317	total: 697ms	remaining: 5.04s
243:	learn: 0.8291317	total: 699ms	remaining: 5.03s
244:	learn: 0.8292683	total: 702ms	remaining: 5.03s
245:	learn: 0.8292284	total: 705ms	remaining: 5.03s
246:	learn: 0.8293651	total: 708ms	remaining: 5.02s
247:	learn: 0.8292284	total: 712ms	remaining: 5.03s
248:	learn: 0.8292854	total: 714ms	remaining: 5.02s
249:	learn: 0.8292854	total: 717ms	remaining: 5.02s
250:	learn: 0.8291087	total: 720ms	remaining: 5.02s
251:	learn: 0.8293424	total: 723ms	remaining: 5.01s
252:	learn: 0.8293025	total: 725ms	remaining: 5.01s
253:	learn: 0.8293025	total: 729ms	remaining: 5.01s
254:	learn: 0.8290289	total: 732ms	remaining: 5.01s
255:	learn: 0.8292797	total: 734ms	remaining: 5s
256:	learn: 0.8295534	total: 737ms	remaining: 5s
257:	learn: 0.8293994	total: 740ms	remaining: 5s
258:	learn: 0.8297300	total: 743ms	remaining: 4.99s
259:	learn: 0.8299240	total: 746ms	remaining: 4.99s
260:	learn: 0.8296902	total: 748ms	remaining: 4.99s
261:	learn: 0.8294166	total: 751ms	remaining: 4.99s
262:	learn: 0.8297474	total: 754ms	remaining: 4.98s
263:	learn: 0.8297076	total: 757ms	remaining: 4.98s
264:	learn: 0.8295136	total: 760ms	remaining: 4.98s
265:	learn: 0.8294166	total: 763ms	remaining: 4.97s
266:	learn: 0.8295136	total: 766ms	remaining: 4.97s
267:	learn: 0.8297474	total: 769ms	remaining: 4.97s
268:	learn: 0.8299813	total: 771ms	remaining: 4.96s
269:	learn: 0.8300784	total: 775ms	remaining: 4.97s
270:	learn: 0.8299415	total: 778ms	remaining: 4.96s
271:	learn: 0.8299415	total: 781ms	remaining: 4.96s
272:	learn: 0.8299017	total: 784ms	remaining: 4.96s
273:	learn: 0.8301754	total: 786ms	remaining: 4.95s
274:	learn: 0.8301754	total: 789ms	remaining: 4.95s
275:	learn: 0.8304272	total: 792ms	remaining: 4.95s
276:	learn: 0.8302328	total: 795ms	remaining: 4.94s
277:	learn: 0.8304272	total: 798ms	remaining: 4.95s
278:	learn: 0.8305243	total: 801ms	remaining: 4.94s
279:	learn: 0.8303875	total: 804ms	remaining: 4.94s
280:	learn: 0.8303875	total: 808ms	remaining: 4.94s
281:	learn: 0.8302505	total: 810ms	remaining: 4.94s
282:	learn: 0.8301533	total: 813ms	remaining: 4.93s
283:	learn: 0.8303875	total: 816ms	remaining: 4.93s
284:	learn: 0.8305819	total: 819ms	remaining: 4.92s
285:	learn: 0.8305819	total: 821ms	remaining: 4.92s
286:	learn: 0.8302682	total: 824ms	remaining: 4.92s
287:	learn: 0.8301710	total: 827ms	remaining: 4.92s
288:	learn: 0.8301710	total: 830ms	remaining: 4.91s
289:	learn: 0.8301710	total: 832ms	remaining: 4.91s
290:	learn: 0.8302108	total: 835ms	remaining: 4.9s
291:	learn: 0.8302108	total: 838ms	remaining: 4.9s
292:	learn: 0.8306395	total: 841ms	remaining: 4.9s
293:	learn: 0.8306395	total: 844ms	remaining: 4.89s
294:	learn: 0.8304450	total: 846ms	remaining: 4.89s
295:	learn: 0.8303477	total: 849ms	remaining: 4.89s
296:	learn: 0.8303080	total: 852ms	remaining: 4.88s
297:	learn: 0.8304052	total: 854ms	remaining: 4.88s
298:	learn: 0.8304052	total: 857ms	remaining: 4.88s
299:	learn: 0.8305025	total: 860ms	remaining: 4.87s
300:	learn: 0.8305025	total: 863ms	remaining: 4.87s
301:	learn: 0.8305998	total: 865ms	remaining: 4.87s
302:	learn: 0.8305025	total: 868ms	remaining: 4.86s
303:	learn: 0.8305422	total: 871ms	remaining: 4.86s
304:	learn: 0.8306792	total: 874ms	remaining: 4.86s
305:	learn: 0.8305422	total: 877ms	remaining: 4.85s
306:	learn: 0.8305998	total: 879ms	remaining: 4.85s
307:	learn: 0.8305998	total: 882ms	remaining: 4.84s
308:	learn: 0.8308918	total: 885ms	remaining: 4.84s
309:	learn: 0.8308341	total: 888ms	remaining: 4.84s
310:	learn: 0.8304450	total: 890ms	remaining: 4.83s
311:	learn: 0.8305422	total: 893ms	remaining: 4.83s
312:	learn: 0.8304450	total: 896ms	remaining: 4.83s
313:	learn: 0.8310107	total: 899ms	remaining: 4.83s
314:	learn: 0.8305422	total: 902ms	remaining: 4.82s
315:	learn: 0.8306395	total: 904ms	remaining: 4.82s
316:	learn: 0.8306395	total: 907ms	remaining: 4.82s
317:	learn: 0.8306792	total: 910ms	remaining: 4.81s
318:	learn: 0.8303655	total: 913ms	remaining: 4.81s
319:	learn: 0.8304231	total: 915ms	remaining: 4.8s
320:	learn: 0.8304628	total: 919ms	remaining: 4.8s
321:	learn: 0.8304628	total: 921ms	remaining: 4.8s
322:	learn: 0.8307368	total: 924ms	remaining: 4.8s
323:	learn: 0.8312449	total: 927ms	remaining: 4.79s
324:	learn: 0.8313422	total: 930ms	remaining: 4.79s
325:	learn: 0.8314396	total: 933ms	remaining: 4.79s
326:	learn: 0.8314396	total: 936ms	remaining: 4.79s
327:	learn: 0.8316925	total: 938ms	remaining: 4.78s
328:	learn: 0.8317899	total: 941ms	remaining: 4.78s
329:	learn: 0.8316530	total: 944ms	remaining: 4.78s
330:	learn: 0.8318875	total: 947ms	remaining: 4.77s
331:	learn: 0.8319850	total: 951ms	remaining: 4.78s
332:	learn: 0.8319850	total: 954ms	remaining: 4.77s
333:	learn: 0.8320826	total: 957ms	remaining: 4.77s
334:	learn: 0.8320826	total: 959ms	remaining: 4.77s
335:	learn: 0.8320826	total: 962ms	remaining: 4.76s
336:	learn: 0.8320826	total: 965ms	remaining: 4.76s
337:	learn: 0.8319456	total: 968ms	remaining: 4.76s
338:	learn: 0.8319456	total: 971ms	remaining: 4.75s
339:	learn: 0.8319850	total: 973ms	remaining: 4.75s
340:	learn: 0.8319850	total: 976ms	remaining: 4.75s
341:	learn: 0.8322195	total: 979ms	remaining: 4.75s
342:	learn: 0.8321219	total: 983ms	remaining: 4.75s
343:	learn: 0.8322195	total: 986ms	remaining: 4.74s
344:	learn: 0.8323564	total: 988ms	remaining: 4.74s
345:	learn: 0.8323171	total: 991ms	remaining: 4.74s
346:	learn: 0.8320826	total: 994ms	remaining: 4.73s
347:	learn: 0.8320826	total: 997ms	remaining: 4.73s
348:	learn: 0.8321801	total: 1000ms	remaining: 4.73s
349:	learn: 0.8323171	total: 1s	remaining: 4.72s
350:	learn: 0.8323564	total: 1s	remaining: 4.72s
351:	learn: 0.8321219	total: 1.01s	remaining: 4.72s
352:	learn: 0.8324540	total: 1.01s	remaining: 4.71s
353:	learn: 0.8324540	total: 1.01s	remaining: 4.72s
354:	learn: 0.8322588	total: 1.02s	remaining: 4.72s
355:	learn: 0.8321219	total: 1.02s	remaining: 4.71s
356:	learn: 0.8321219	total: 1.02s	remaining: 4.71s
357:	learn: 0.8318480	total: 1.03s	remaining: 4.71s
358:	learn: 0.8318480	total: 1.03s	remaining: 4.71s
359:	learn: 0.8319062	total: 1.03s	remaining: 4.7s
360:	learn: 0.8318086	total: 1.03s	remaining: 4.7s
361:	learn: 0.8320432	total: 1.04s	remaining: 4.7s
362:	learn: 0.8320432	total: 1.04s	remaining: 4.69s
363:	learn: 0.8325516	total: 1.04s	remaining: 4.69s
364:	learn: 0.8324540	total: 1.04s	remaining: 4.68s
365:	learn: 0.8325516	total: 1.05s	remaining: 4.68s
366:	learn: 0.8325123	total: 1.05s	remaining: 4.68s
367:	learn: 0.8326100	total: 1.05s	remaining: 4.67s
368:	learn: 0.8327076	total: 1.06s	remaining: 4.67s
369:	learn: 0.8325707	total: 1.06s	remaining: 4.67s
370:	learn: 0.8322967	total: 1.06s	remaining: 4.67s
371:	learn: 0.8325314	total: 1.06s	remaining: 4.66s
372:	learn: 0.8325314	total: 1.07s	remaining: 4.66s
373:	learn: 0.8325314	total: 1.07s	remaining: 4.66s
374:	learn: 0.8325314	total: 1.07s	remaining: 4.65s
375:	learn: 0.8326291	total: 1.08s	remaining: 4.65s
376:	learn: 0.8326291	total: 1.08s	remaining: 4.65s
377:	learn: 0.8326291	total: 1.08s	remaining: 4.64s
378:	learn: 0.8325707	total: 1.08s	remaining: 4.64s
379:	learn: 0.8323360	total: 1.09s	remaining: 4.64s
380:	learn: 0.8326684	total: 1.09s	remaining: 4.63s
381:	learn: 0.8330008	total: 1.09s	remaining: 4.63s
382:	learn: 0.8328246	total: 1.1s	remaining: 4.63s
383:	learn: 0.8329616	total: 1.1s	remaining: 4.62s
384:	learn: 0.8330594	total: 1.1s	remaining: 4.62s
385:	learn: 0.8328246	total: 1.1s	remaining: 4.62s
386:	learn: 0.8328246	total: 1.11s	remaining: 4.61s

0.6298472385428907

In [288]:
import xgboost as xgb

model = xgb.XGBClassifier(
    n_estimators=50,
    random_state=42
)
model.fit(X_train, y_train)

# Предсказание и оценка точности
y_pred = model.predict(X_test)
f1_score(y_test, y_pred)

0.5750708215297451